version: "3"

services:
  mysql:
    container_name: ortopedica-mysql
    image: mysql:5.7.21
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  api-conta:
    container_name: api-conta
    image: fernandoe/fe-conta-api:0.0.1
    ports:
      - "9000:8000"
    volumes:
      - ../fe-conta-api/src:/app
    depends_on:
      - mysql
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql:3306/conta
      VERSION: 0.0.1
      no_proxy: mysql
    stdin_open: true
    tty: true

  api-pessoa:
    container_name: api-pessoa
    image: fernandoe/fe-pessoa-api:0.0.1
    ports:
      - "9001:8000"
    volumes:
      - ../fe-pessoa-api/src:/app
    depends_on:
      - mysql
      - api-conta
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql:3306/pessoa
      no_proxy: mysql,conta
    stdin_open: true
    tty: true

  api-endereco:
    container_name: api-endereco
    image: fernandoe/fe-endereco-api:0.0.1
    ports:
      - "9002:8000"
    volumes:
      - ../fe-endereco-api/src:/app
    depends_on:
      - mysql
      - api-conta
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql:3306/endereco
      no_proxy: mysql,conta
    stdin_open: true
    tty: true

  api-ortopedica:
    container_name: api-ortopedica
    # build: ../fe-ortopedica-api
    image: fernandoe/fe-ortopedica-api:0.0.5
    ports:
      - "9003:8000"
    volumes:
      - ../fe-ortopedica-api/src:/app
    depends_on:
      - mysql
      - api-conta
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql:3306/ortopedica
      CONTA_SERVICE_HOST: 'api-conta'
      no_proxy: mysql,conta
    stdin_open: true
    tty: true

  ortopedica:
    container_name: ortopedica
    image: fernandoe/ortopedica:0.0.1
    # image: fernandoe/ortopedica:local
    build:
      context: ../ortopedica
    #   dockerfile: Dockerfile.devenv.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ../ortopedica:/app

volumes:
  mysql-data:
